### PR TITLE
Ui modif

### PR DESCRIPTION
**Pull request by saleiva**
@danicarrion CR, please

### CODE REVIEW

**Comment by danicarrion** [comment]
:thumbsup:

i just added the new url params in the description in index.html and use the new url in the readme

**Comment by saleiva** [comment]
merged!

**Comment by danicarrion** [comment]
deployed to labs: http://multilayer.cartodb.io/

**Comment by jatorre** [comment]
Hey guys,

This looks great, but I think is a bit too big. Consider this is what GME looks like

screen shot 2015-02-18 at 1 30 59 am

http://leicester.gov.uk/your-council-services/ep/the-environment/climate-change/renewable-map/

If we put that size of a layer selector this is how it will look on their page

screen shot 2015-02-18 at 1 33 51 am

I think we need something a bit smaller to make it fit on an embed.

**Pull request merged**
